In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

In [2]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
x.dtype

dtype('int32')

In [4]:
x.shape

(5,)

In [6]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(Y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
Y.shape

(4, 3)

In [8]:
Y.size

12

In [11]:
X = np.zeros((3,4))
print(X)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
X = np.full((4, 3), 5)
print(X)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [14]:
X = np.eye(5)
print(X)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
X = np.diag([10, 20, 30, 50])
print(X)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


In [17]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
x = np.arange(4, 10)
print(x)

[4 5 6 7 8 9]


In [19]:
x = np.arange(1, 14, 3)
print(x)

[ 1  4  7 10 13]


In [20]:
x = np.linspace(0, 25, 10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [21]:
x = np.linspace(0, 25, 10, endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [32]:
x = np.arange(20)
print("arange 1D: ", x)
y = np.reshape(x, (4, 5))
print("\nreshaped 2D: \n", y, "\n")

try:
    z = np.reshape(x, (5, 5))
except ValueError:
    print("Z will fail with ValueError, it cannot reshape array of size 20 into shape (5,5)!")

arange 1D:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

reshaped 2D: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

Z will fail with ValueError, it cannot reshape array of size 20 into shape (5,5)!


In [33]:
random_array = np.random.random((3, 3))
print(random_array)

[[0.01385649 0.9258945  0.52263519]
 [0.91466573 0.65838074 0.1811005 ]
 [0.67326031 0.28568811 0.34354034]]


In [34]:
random_int = np.random.randint(4, 15, (3, 2))
print(random_int)

[[ 5 14]
 [ 4  7]
 [11  7]]


In [38]:
random_normal_dist = np.random.normal(0, 0.1, size=(1000,1000))
print("This gives a 1000x1000 array of normal/gaussian distribution w/ mean=0, std dev=0.1 \n")
print(random_normal_dist)

This gives a 1000x1000 array of normal/gaussian distribution w/ mean=0, std dev=0.1 

[[ 0.01289667  0.05276966  0.02824236 ...  0.10514806 -0.05108906
  -0.11072513]
 [-0.02823885 -0.00574846  0.07580092 ... -0.05632063 -0.04207828
   0.08787688]
 [ 0.05710716  0.06211718 -0.0345226  ... -0.18413866 -0.21544777
  -0.11084232]
 ...
 [-0.08738216  0.01107896  0.05358118 ...  0.08788401 -0.00378445
   0.18901478]
 [ 0.18159284  0.07810318 -0.16273987 ... -0.19324793 -0.16538658
   0.17882044]
 [-0.23059794  0.01727862  0.1445534  ... -0.02650837 -0.05755347
  -0.03615493]]


In [39]:
print('mean: ', random_normal_dist.mean())
print('std: ', random_normal_dist.std())
print('max: ', random_normal_dist.max())
print('min: ', random_normal_dist.min())
print('# positives: ', (random_normal_dist > 0).sum())
print('# negatives: ', (random_normal_dist < 0).sum())

mean:  -4.867316097159501e-05
std:  0.10011803168452399
max:  0.48844677520684626
min:  -0.47381662049814804
# positives:  499489
# negatives:  500511


<b>Accessing, Deleting, and Inserting Elements Into ndarrays</b>

In [2]:
import numpy as np
ex_index = np.array([1, 2, 3, 4, 5])
print(ex_index)

[1 2 3 4 5]


In [3]:
print('1st: ', ex_index[0])
print('2nd: ', ex_index[1])
print('3rd: ', ex_index[2])

1st:  1
2nd:  2
3rd:  3


In [4]:
ex_index[3] = 20
print(ex_index)

[ 1  2  3 20  5]


In [10]:
ex_index2 = np.arange(1, 10)
print(ex_index2, "\n")
ex_index2 = ex_index2.reshape(3, 3)
print(ex_index2)

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print("Element at (0, 0): ", ex_index2[0, 0])
print("Element at (0, 1): ", ex_index2[0, 1])
print("Element at (2, 2): ", ex_index2[2, 2])

Element at (0, 0):  1
Element at (0, 1):  2
Element at (2, 2):  9


In [12]:
ex_index2[0, 0] = 20
print(ex_index2)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [15]:
ex_del = np.array([1, 2, 3, 4, 5])
print(ex_del)

ex_del = np.delete(ex_del, [0, 4])
print(ex_del)

[1 2 3 4 5]
[2 3 4]


In [20]:
ex_del2 = np.arange(1, 10).reshape(3, 3)
print(ex_del2)

ex_del2_row = np.delete(ex_del2, 0, axis=0)
print("\n", ex_del2_row)

ex_del2_col = np.delete(ex_del2, [0, 2], axis=1)
print("\n", ex_del2_col)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2]
 [5]
 [8]]


In [24]:
ex_append = np.array([1,2,3,4,5])
print(ex_append)

ex_append = np.append(ex_append, [6])
print(ex_append)

ex_append = np.append(ex_append, [7,8,9])
print(ex_append)

[1 2 3 4 5]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8 9]


In [35]:
ex_append2 = np.arange(1, 10).reshape(3, 3)
print(ex_append2)

ex_append2 = np.append(ex_append2, [[10, 11, 12]], axis=0)
print("\n", ex_append2)

ex_append2 = np.append(ex_append2, [[6],[15],[24], [34]], axis=1)
print("\n", ex_append2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 [[ 1  2  3  6]
 [ 4  5  6 15]
 [ 7  8  9 24]
 [10 11 12 34]]


In [37]:
ex_insert = np.array([1,2,5,6,7])
print(ex_insert)

ex_insert = np.insert(ex_insert, 2, [3,4])
print("\n", ex_insert)

[1 2 5 6 7]

 [1 2 3 4 5 6 7]


In [43]:
ex_insert2 = np.array([[1,2,3], [7,8,9]])
print(ex_insert2)

ex_insert2 = np.insert(ex_insert2, 1, [4,5,6], axis=0)
print("\n", ex_insert2)

ex_insert2 = np.insert(ex_insert2, 1, 5, axis=1)
print("\n", ex_insert2)

[[1 2 3]
 [7 8 9]]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[1 5 2 3]
 [4 5 5 6]
 [7 5 8 9]]


In [48]:
stack_single = np.array([1,2])
print(stack_single)

stack_multi = np.array([[3,4], [5,6]])
print("\n", stack_multi)

vert_stack = np.vstack([stack_single, stack_multi])
print("\n", vert_stack)

horiz_stack = np.hstack([stack_single.reshape(2, 1), stack_multi])
print("\n", horiz_stack)

[1 2]

 [[3 4]
 [5 6]]

 [[1 2]
 [3 4]
 [5 6]]

 [[1 3 4]
 [2 5 6]]
